# Generated by Django 4.2.4 on 2025-08-05 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('is_deletable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_part_count', models.SmallIntegerField(default=1)),
                ('failure_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.CharField(blank=True, max_length=1600, null=True)),
                ('receivers', models.TextField(blank=True, null=True)),
                ('receiver_count', models.IntegerField()),
                ('success_count', models.IntegerField()),
                ('fail_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_part_count', models.SmallIntegerField(default=1)),
                ('receiver', models.TextField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1600, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('failed', 'Failed'), ('sent', 'Sent')], max_length=20, null=True)),
                ('sms_type', models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20, null=True)),
                ('gateway_type', models.CharField(blank=True, choices=[('https', 'HTTPS'), ('panel', 'Panel')], max_length=20, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sms_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.smsapi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bill_type', models.CharField(blank=True, choices=[('prepaid', 'Prepaid'), ('postpaid_limited', 'Postpaid Limited'), ('postpaid_unlimited', 'Postpaid Unlimited')], default='prepaid', max_length=20, null=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('masking_national_msg_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_national_msg_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('masking_internation_msg_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_internation_msg_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('prefix_based', models.BooleanField(default=False)),
                ('masking_prefix_013_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_prefix_013_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('masking_prefix_014_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_prefix_014_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('masking_prefix_015_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_prefix_015_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('masking_prefix_016_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_prefix_016_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('masking_prefix_017_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_prefix_017_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('masking_prefix_018_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_prefix_018_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('masking_prefix_019_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_masking_prefix_019_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_owner_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('after_operation_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_sms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_sms_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignSmsAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sms_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.smsapi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
