# Generated by Django 4.2.4 on 2025-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchase",
            name="paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
