# Generated by Django 4.2.4 on 2025-08-07 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_group_options_alter_group_name"),
        ("purchase", "0002_purchase_due_purchase_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="payment_ledger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="accounts.ledgeraccount",
            ),
        ),
    ]
