# Generated by Django 4.2.4 on 2025-08-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_group_options_alter_group_name"),
        ("purchase", "0003_purchase_payment_ledger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="payment_ledger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="purchases_payment",
                to="accounts.ledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_purchases",
                to="accounts.ledgeraccount",
            ),
        ),
    ]
