# Generated by Django 4.2.4 on 2025-08-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_alter_purchase_payment_ledger_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="invoice_number",
            field=models.CharField(max_length=100),
        ),
    ]
