# Generated by Django 4.2.4 on 2025-08-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_supplier_customer'),
        ('purchase', '0005_alter_purchase_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_purchases', to='authentication.supplier'),
        ),
    ]
