from enum import Enum


class PermissionEnum(Enum):

# ENUM FOR 'AUTHENTIACTION' APP	

	# PERMISSION PERMISSION
	PERMISSION_CREATE = 'PERMISSION_CREATE'
	PERMISSION_UPDATE = 'PERMISSION_UPDATE'
	PERMISSION_PARTIAL_UPDATE = 'PERMISSION_PARTIAL_UPDATE'
	PERMISSION_DELETE = 'PERMISSION_DELETE'
	PERMISSION_LIST = 'PERMISSION_LIST'
	PERMISSION_DETAILS = 'PERMISSION_DETAILS'

	# ROLE PERMISSION
	ROLE_CREATE = 'ROLE_CREATE'
	ROLE_UPDATE = 'ROLE_UPDATE'
	ROLE_DELETE = 'ROLE_DELETE'
	ROLE_LIST = 'ROLE_LIST'
	ROLE_DETAILS = 'ROLE_DETAILS'

	# COUNTRY PERMISSION
	COUNTRY_CREATE = 'COUNTRY_CREATE'
	COUNTRY_UPDATE = 'COUNTRY_UPDATE'
	COUNTRY_DELETE = 'COUNTRY_DELETE'
	COUNTRY_LIST = 'COUNTRY_LIST'
	COUNTRY_DETAILS = 'COUNTRY_DETAILS'

	# CITY PERMISSION
	CITY_CREATE = 'CITY_CREATE'
	CITY_UPDATE = 'CITY_UPDATE'
	CITY_DELETE = 'CITY_DELETE'
	CITY_LIST = 'CITY_LIST'
	CITY_DETAILS = 'CITY_DETAILS'

	# THANA PERMISSION
	THANA_CREATE = 'THANA_CREATE'
	THANA_UPDATE = 'THANA_UPDATE'
	THANA_DELETE = 'THANA_DELETE'
	THANA_LIST = 'THANA_LIST'
	THANA_DETAILS = 'THANA_DETAILS'

	# AREA PERMISSION
	AREA_CREATE = 'AREA_CREATE'
	AREA_UPDATE = 'AREA_UPDATE'
	AREA_DELETE = 'AREA_DELETE'
	AREA_LIST = 'AREA_LIST'
	AREA_DETAILS = 'AREA_DETAILS'

	# BRANCH PERMISSION
	BRANCH_CREATE = 'BRANCH_CREATE'
	BRANCH_UPDATE = 'BRANCH_UPDATE'
	BRANCH_DELETE = 'BRANCH_DELETE'
	BRANCH_LIST = 'BRANCH_LIST'
	BRANCH_DETAILS = 'BRANCH_DETAILS'

	# USER PERMISSIONS
	USER_CREATE = 'USER_CREATE'
	USER_UPDATE = 'USER_UPDATE'
	USER_PARTIAL_UPDATE = 'USER_PARTIAL_UPDATE'
	USER_DELETE = 'USER_DELETE'
	USER_LIST = 'USER_LIST'
	USER_DETAILS = 'USER_DETAILS'

	# DEPARTMENT PERMISSION
	DEPARTMENT_CREATE = 'DEPARTMENT_CREATE'
	DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE'
	DEPARTMENT_DELETE = 'DEPARTMENT_DELETE'
	DEPARTMENT_LIST = 'DEPARTMENT_LIST'
	DEPARTMENT_DETAILS = 'DEPARTMENT_DETAILS'

	# EMPLOYEE PERMISSION
	EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
	EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
	EMPLOYEE_DELETE = 'EMPLOYEE_DELETE'
	EMPLOYEE_LIST = 'EMPLOYEE_LIST'
	EMPLOYEE_DETAILS = 'EMPLOYEE_DETAILS'

	# CUSTOMER PERMISSION
	CUSTOMER_TYPE_CREATE = 'CUSTOMER_TYPE_CREATE'
	CUSTOMER_TYPE_UPDATE = 'CUSTOMER_TYPE_UPDATE'
	CUSTOMER_TYPE_DELETE = 'CUSTOMER_TYPE_DELETE'
	CUSTOMER_TYPE_LIST = 'CUSTOMER_TYPE_LIST'
	CUSTOMER_TYPE_DETAILS = 'CUSTOMER_TYPE_DETAILS'

	# CUSTOMER PERMISSION
	CUSTOMER_CREATE = 'CUSTOMER_CREATE'
	CUSTOMER_UPDATE = 'CUSTOMER_UPDATE'
	CUSTOMER_DELETE = 'CUSTOMER_DELETE'
	CUSTOMER_LIST = 'CUSTOMER_LIST'
	CUSTOMER_DETAILS = 'CUSTOMER_DETAILS'

	# QUALIFICATION PERMISSION
	QUALIFICATION_CREATE = 'QUALIFICATION_CREATE'
	QUALIFICATION_UPDATE = 'QUALIFICATION_UPDATE'
	QUALIFICATION_DELETE = 'QUALIFICATION_DELETE'
	QUALIFICATION_LIST = 'QUALIFICATION_LIST'
	QUALIFICATION_DETAILS = 'QUALIFICATION_DETAILS'



# ENUM FOR 'PRODUCT' APP

	# PRODUCT PERMISSION
	PRODUCT_CREATE = 'PRODUCT_CREATE'
	PRODUCT_UPDATE = 'PRODUCT_UPDATE'
	PRODUCT_DELETE = 'PRODUCT_DELETE'
	PRODUCT_LIST = 'PRODUCT_LIST'
	PRODUCT_DETAILS = 'PRODUCT_DETAILS'

	# PRODUCT_TAG PERMISSION
	PRODUCT_TAG_CREATE = 'PRODUCT_TAG_CREATE'
	PRODUCT_TAG_UPDATE = 'PRODUCT_TAG_UPDATE'
	PRODUCT_TAG_DELETE = 'PRODUCT_TAG_DELETE'
	PRODUCT_TAG_LIST = 'PRODUCT_TAG_LIST'
	PRODUCT_TAG_DETAILS = 'PRODUCT_TAG_DETAILS'

	# ATTRIBUTE_SET PERMISSION
	ATTRIBUTE_SET_CREATE = 'ATTRIBUTE_SET_CREATE'
	ATTRIBUTE_SET_UPDATE = 'ATTRIBUTE_SET_UPDATE'
	ATTRIBUTE_SET_DELETE = 'ATTRIBUTE_SET_DELETE'
	ATTRIBUTE_SET_LIST = 'ATTRIBUTE_SET_LIST'
	ATTRIBUTE_SET_DETAILS = 'QUALIFICATION_DETAILS'

	# ATTRIBUTE_VALUE PERMISSION
	ATTRIBUTE_VALUE_CREATE = 'ATTRIBUTE_VALUE_CREATE'
	ATTRIBUTE_VALUE_UPDATE = 'ATTRIBUTE_VALUE_UPDATE'
	ATTRIBUTE_VALUE_DELETE = 'ATTRIBUTE_VALUE_DELETE'
	ATTRIBUTE_VALUE_LIST = 'ATTRIBUTE_VALUE_LIST'
	ATTRIBUTE_VALUE_DETAILS = 'ATTRIBUTE_VALUE_DETAILS'

	# ATTRIBUTE PERMISSION
	ATTRIBUTE_CREATE = 'ATTRIBUTE_CREATE'
	ATTRIBUTE_UPDATE = 'ATTRIBUTE_UPDATE'
	ATTRIBUTE_DELETE = 'ATTRIBUTE_DELETE'
	ATTRIBUTE_LIST = 'ATTRIBUTE_LIST'
	ATTRIBUTE_DETAILS = 'ATTRIBUTE_DETAILS'

	# BRAND PERMISSION
	BRAND_CREATE = 'BRAND_CREATE'
	BRAND_UPDATE = 'BRAND_UPDATE'
	BRAND_DELETE = 'BRAND_DELETE'
	BRAND_LIST = 'BRAND_LIST'
	BRAND_DETAILS = 'BRAND_DETAILS'

	# CATEGORY PERMISSION
	CATEGORY_CREATE = 'CATEGORY_CREATE'
	CATEGORY_UPDATE = 'CATEGORY_UPDATE'
	CATEGORY_DELETE = 'CATEGORY_DELETE'
	CATEGORY_LIST = 'CATEGORY_LIST'
	CATEGORY_DETAILS = 'CATEGORY_DETAILS'

	# MANUFACTURER PERMISSION
	MANUFACTURER_CREATE = 'MANUFACTURER_CREATE'
	MANUFACTURER_UPDATE = 'MANUFACTURER_UPDATE'
	MANUFACTURER_DELETE = 'MANUFACTURER_DELETE'
	MANUFACTURER_LIST = 'MANUFACTURER_LIST'
	MANUFACTURER_DETAILS = 'MANUFACTURER_DETAILS'


	# COLOR PERMISSION
	COLOR_CREATE = 'COLOR_CREATE'
	COLOR_UPDATE = 'COLOR_UPDATE'
	COLOR_DELETE = 'COLOR_DELETE'
	COLOR_LIST = 'COLOR_LIST'
	COLOR_DETAILS = 'COLOR_DETAILS'


	# SIZE PERMISSION
	SIZE_CREATE = 'SIZE_CREATE'
	SIZE_UPDATE = 'SIZE_UPDATE'
	SIZE_DELETE = 'SIZE_DELETE'
	SIZE_LIST = 'SIZE_LIST'
	SIZE_DETAILS = 'SIZE_DETAILS'


	# PRODUCT_IMAGE PERMISSION
	PRODUCT_IMAGE_CREATE = 'PRODUCT_IMAGE_CREATE'
	PRODUCT_IMAGE_UPDATE = 'PRODUCT_IMAGE_UPDATE'
	PRODUCT_IMAGE_DELETE = 'PRODUCT_IMAGE_DELETE'
	PRODUCT_IMAGE_LIST = 'PRODUCT_IMAGE_LIST'
	PRODUCT_IMAGE_DETAILS = 'PRODUCT_IMAGE_DETAILS'




	# ENUM FOR 'ORDER' APP

	# PAYMENT_METHOD PERMISSION
	PAYMENT_METHOD_CREATE = 'PAYMENT_METHOD_CREATE'
	PAYMENT_METHOD_UPDATE = 'PAYMENT_METHOD_UPDATE'
	PAYMENT_METHOD_DELETE = 'PAYMENT_METHOD_DELETE'
	PAYMENT_METHOD_LIST = 'PAYMENT_METHOD_LIST'
	PAYMENT_METHOD_DETAILS = 'PAYMENT_METHOD_DETAILS'

	# ORDER_STATUS PERMISSION
	ORDER_STATUS_CREATE = 'ORDER_STATUS_CREATE'
	ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE'
	ORDER_STATUS_DELETE = 'ORDER_STATUS_DELETE'
	ORDER_STATUS_LIST = 'ORDER_STATUS_LIST'
	ORDER_STATUS_DETAILS = 'ORDER_STATUS_DETAILS'

	# ORDER PERMISSION
	ORDER_CREATE = 'ORDER_CREATE'
	ORDER_UPDATE = 'ORDER_UPDATE'
	ORDER_DELETE = 'ORDER_DELETE'
	ORDER_LIST = 'ORDER_LIST'
	ORDER_DETAILS = 'ORDER_DETAILS'

	# ORDER_ITEM PERMISSION
	ORDER_ITEM_CREATE = 'ORDER_ITEM_CREATE'
	ORDER_ITEM_UPDATE = 'ORDER_ITEM_UPDATE'
	ORDER_ITEM_DELETE = 'ORDER_ITEM_DELETE'
	ORDER_ITEM_LIST = 'ORDER_ITEM_LIST'
	ORDER_ITEM_DETAILS = 'ORDER_ITEM_DETAILS'

	# SHIPPING_ADDRESS PERMISSION
	SHIPPING_ADDRESS_CREATE = 'SHIPPING_ADDRESS_CREATE'
	SHIPPING_ADDRESS_UPDATE = 'SHIPPING_ADDRESS_UPDATE'
	SHIPPING_ADDRESS_DELETE = 'SHIPPING_ADDRESS_DELETE'
	SHIPPING_ADDRESS_LIST = 'SHIPPING_ADDRESS_LIST'
	SHIPPING_ADDRESS_DETAILS = 'SHIPPING_ADDRESS_DETAILS'




class AccountPermEnum(Enum):
	# GROUP PERMISSIONS
	PRIMARY_GROUP_CREATE = 'PRIMARY_GROUP_CREATE'
	PRIMARY_GROUP_UPDATE = 'PRIMARY_GROUP_UPDATE'
	PRIMARY_GROUP_PARTIAL_UPDATE = 'PRIMARY_GROUP_PARTIAL_UPDATE'
	PRIMARY_GROUP_DELETE = 'PRIMARY_GROUP_DELETE'
	PRIMARY_GROUP_LIST = 'PRIMARY_GROUP_LIST'
	PRIMARY_GROUP_DETAILS = 'PRIMARY_GROUP_DETAILS'

	# GROUP PERMISSIONS
	GROUP_CREATE = 'GROUP_CREATE'
	GROUP_UPDATE = 'GROUP_UPDATE'
	GROUP_PARTIAL_UPDATE = 'GROUP_PARTIAL_UPDATE'
	GROUP_DELETE = 'GROUP_DELETE'
	GROUP_LIST = 'GROUP_LIST'
	GROUP_DETAILS = 'GROUP_DETAILS'

	# LEDGER_ACCOUNT PERMISSIONS
	LEDGER_ACCOUNT_CREATE = 'LEDGER_ACCOUNT_CREATE'
	LEDGER_ACCOUNT_UPDATE = 'LEDGER_ACCOUNT_UPDATE'
	LEDGER_ACCOUNT_PARTIAL_UPDATE = 'LEDGER_ACCOUNT_PARTIAL_UPDATE'
	LEDGER_ACCOUNT_DELETE = 'LEDGER_ACCOUNT_DELETE'
	LEDGER_ACCOUNT_LIST = 'LEDGER_ACCOUNT_LIST'
	LEDGER_ACCOUNT_DETAILS = 'LEDGER_ACCOUNT_DETAILS'

	# SUBLEDGER PERMISSION
	SUBLEDGER_ACCOUNT_CREATE = 'SUBLEDGER_ACCOUNT_CREATE'
	SUBLEDGER_ACCOUNT_UPDATE = 'SUBLEDGER_ACCOUNT_UPDATE'
	SUBLEDGER_ACCOUNT_DELETE = 'SUBLEDGER_ACCOUNT_DELETE'
	SUBLEDGER_ACCOUNT_LIST = 'SUBLEDGER_ACCOUNT_LIST'
	SUBLEDGER_ACCOUNT_DETAILS = 'SUBLEDGER_ACCOUNT_DETAILS'

	# PAYMENT_VOUCHER PERMISSION
	PAYMENT_VOUCHER_CREATE = 'PAYMENT_VOUCHER_CREATE'
	PAYMENT_VOUCHER_UPDATE = 'PAYMENT_VOUCHER_UPDATE'
	PAYMENT_VOUCHER_DELETE = 'PAYMENT_VOUCHER_DELETE'
	PAYMENT_VOUCHER_LIST = 'PAYMENT_VOUCHER_LIST'
	PAYMENT_VOUCHER_DETAILS = 'PAYMENT_VOUCHER_DETAILS'

	# RECEIPT_VOUCHER PERMISSION
	RECEIPT_VOUCHER_CREATE = 'RECEIPT_VOUCHER_CREATE'
	RECEIPT_VOUCHER_UPDATE = 'RECEIPT_VOUCHER_UPDATE'
	RECEIPT_VOUCHER_DELETE = 'RECEIPT_VOUCHER_DELETE'
	RECEIPT_VOUCHER_LIST = 'RECEIPT_VOUCHER_LIST'
	RECEIPT_VOUCHER_DETAILS = 'RECEIPT_VOUCHER_DETAILS'

	# SALES PERMISSION
	SALES_CREATE = 'SALES_CREATE'
	SALES_UPDATE = 'SALES_UPDATE'
	SALES_DELETE = 'SALES_DELETE'
	SALES_LIST = 'SALES_LIST'
	SALES_DETAILS = 'SALES_DETAILS'

	# PURCHASE PERMISSION
	PURCHASE_CREATE = 'PURCHASE_CREATE'
	PURCHASE_UPDATE = 'PURCHASE_UPDATE'
	PURCHASE_DELETE = 'PURCHASE_DELETE'
	PURCHASE_LIST = 'PURCHASE_LIST'
	PURCHASE_DETAILS = 'PURCHASE_DETAILS'

	# CONTRA PERMISSION
	CONTRA_CREATE = 'CONTRA_CREATE'
	CONTRA_UPDATE = 'CONTRA_UPDATE'
	CONTRA_DELETE = 'CONTRA_DELETE'
	CONTRA_LIST = 'CONTRA_LIST'
	CONTRA_DETAILS = 'CONTRA_DETAILS'

	# JOURNAL PERMISSION
	JOURNAL_CREATE = 'JOURNAL_CREATE'
	JOURNAL_UPDATE = 'JOURNAL_UPDATE'
	JOURNAL_DELETE = 'JOURNAL_DELETE'
	JOURNAL_LIST = 'JOURNAL_LIST'
	JOURNAL_DETAILS = 'JOURNAL_DETAILS'

	# IDJOURNAL PERMISSION
	IDJOURNAL_CREATE = 'IDJOURNAL_CREATE'
	IDJOURNAL_UPDATE = 'IDJOURNAL_UPDATE'
	IDJOURNAL_DELETE = 'IDJOURNAL_DELETE'
	IDJOURNAL_LIST = 'IDJOURNAL_LIST'
	IDJOURNAL_DETAILS = 'IDJOURNAL_DETAILS'

	# ACCOUNT_LOG PERMISSION
	ACCOUNT_LOG_CREATE = 'ACCOUNT_LOG_CREATE'
	ACCOUNT_LOG_UPDATE = 'ACCOUNT_LOG_UPDATE'
	ACCOUNT_LOG_DELETE = 'ACCOUNT_LOG_DELETE'
	ACCOUNT_LOG_LIST = 'ACCOUNT_LOG_LIST'
	ACCOUNT_LOG_DETAILS = 'ACCOUNT_LOG_DETAILS'

	# ACCOUNT_UPDATE_PERMISSION PERMISSION
	ACCOUNT_UPDATE_PERMISSION_CREATE = 'ACCOUNT_UPDATE_PERMISSION_CREATE'
	ACCOUNT_UPDATE_PERMISSION_UPDATE = 'ACCOUNT_UPDATE_PERMISSION_UPDATE'
	ACCOUNT_UPDATE_PERMISSION_DELETE = 'ACCOUNT_UPDATE_PERMISSION_DELETE'
	ACCOUNT_UPDATE_PERMISSION_LIST = 'ACCOUNT_UPDATE_PERMISSION_LIST'
	ACCOUNT_UPDATE_PERMISSION_DETAILS = 'ACCOUNT_UPDATE_PERMISSION_DETAILS'

	# PAYMENT_VOIUCHER_REPORT PERMISSION
	PAYMENT_VOIUCHER_REPORT_LIST = 'PAYMENT_VOIUCHER_REPORT_LIST'
	PAYMENT_VOIUCHER_SUMMARY_LIST = 'PAYMENT_VOIUCHER_SUMMARY_LIST'

	# RECEIPT_VOIUCHER_REPORT PERMISSION
	RECEIPT_VOIUCHER_REPORT_LIST = 'RECEIPT_VOIUCHER_REPORT_LIST'
	RECEIPT_VOIUCHER_SUMMARY_LIST = 'RECEIPT_VOIUCHER_SUMMARY_LIST'

	# SALES_REPORT PERMISSION
	SALES_REPORT_LIST = 'SALES_REPORT_LIST'
	SALES_SUMMARY_LIST = 'SALES_SUMMARY_LIST'

	# PURCHASE_REPORT PERMISSION
	PURCHASE_REPORT_LIST = 'PURCHASE_REPORT_LIST'
	PURCHASE_SUMMARY_LIST = 'PURCHASE_SUMMARY_LIST'

	# CONTRA_REPORT PERMISSION
	CONTRA_REPORT_LIST = 'CONTRA_REPORT_LIST'

	# ACCOUNT_LOG_REPORT PERMISSION
	ACCOUNT_LOG_REPORT_GENERAL = 'ACCOUNT_LOG_REPORT_GENERAL'
	ACCOUNT_LOG_REPORT_BY_LEDGER_TYPE = 'ACCOUNT_LOG_REPORT_BY_LEDGER_TYPE'
	ACCOUNT_LOG_REPORT_CASH_BANK = 'ACCOUNT_LOG_REPORT_CASH_BANK'


	# BALANCE SHEET
	BALANCE_SHEET_LIST = 'BALANCE_SHEET_LIST'
	PROFIT_LOSS_LIST = 'PROFIT_LOSS_LIST'
	TRIAL_BALANCE_LIST = 'TRIAL_BALANCE_LIST'




class AuthPermEnum(Enum):
# ENUM FOR 'AUTHENTIACTION' APP	

	# PERMISSION PERMISSION
	PERMISSION_CREATE = 'PERMISSION_CREATE'
	PERMISSION_UPDATE = 'PERMISSION_UPDATE'
	PERMISSION_PARTIAL_UPDATE = 'PERMISSION_PARTIAL_UPDATE'
	PERMISSION_DELETE = 'PERMISSION_DELETE'
	PERMISSION_LIST = 'PERMISSION_LIST'
	PERMISSION_DETAILS = 'PERMISSION_DETAILS'

	# ROLE PERMISSION
	ROLE_CREATE = 'ROLE_CREATE'
	ROLE_UPDATE = 'ROLE_UPDATE'
	ROLE_DELETE = 'ROLE_DELETE'
	ROLE_LIST = 'ROLE_LIST'
	ROLE_DETAILS = 'ROLE_DETAILS'

	# COUNTRY PERMISSION
	COUNTRY_CREATE = 'COUNTRY_CREATE'
	COUNTRY_UPDATE = 'COUNTRY_UPDATE'
	COUNTRY_DELETE = 'COUNTRY_DELETE'
	COUNTRY_LIST = 'COUNTRY_LIST'
	COUNTRY_DETAILS = 'COUNTRY_DETAILS'

	# CITY PERMISSION
	CITY_CREATE = 'CITY_CREATE'
	CITY_UPDATE = 'CITY_UPDATE'
	CITY_DELETE = 'CITY_DELETE'
	CITY_LIST = 'CITY_LIST'
	CITY_DETAILS = 'CITY_DETAILS'

	# THANA PERMISSION
	THANA_CREATE = 'THANA_CREATE'
	THANA_UPDATE = 'THANA_UPDATE'
	THANA_DELETE = 'THANA_DELETE'
	THANA_LIST = 'THANA_LIST'
	THANA_DETAILS = 'THANA_DETAILS'

	# AREA PERMISSION
	AREA_CREATE = 'AREA_CREATE'
	AREA_UPDATE = 'AREA_UPDATE'
	AREA_DELETE = 'AREA_DELETE'
	AREA_LIST = 'AREA_LIST'
	AREA_DETAILS = 'AREA_DETAILS'

	# BRANCH PERMISSION
	BRANCH_CREATE = 'BRANCH_CREATE'
	BRANCH_UPDATE = 'BRANCH_UPDATE'
	BRANCH_DELETE = 'BRANCH_DELETE'
	BRANCH_LIST = 'BRANCH_LIST'
	BRANCH_DETAILS = 'BRANCH_DETAILS'

	# USER PERMISSIONS
	USER_CREATE = 'USER_CREATE'
	USER_UPDATE = 'USER_UPDATE'
	USER_PARTIAL_UPDATE = 'USER_PARTIAL_UPDATE'
	USER_DELETE = 'USER_DELETE'
	USER_LIST = 'USER_LIST'
	USER_DETAILS = 'USER_DETAILS'

	# DEPARTMENT PERMISSION
	DEPARTMENT_CREATE = 'DEPARTMENT_CREATE'
	DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE'
	DEPARTMENT_DELETE = 'DEPARTMENT_DELETE'
	DEPARTMENT_LIST = 'DEPARTMENT_LIST'
	DEPARTMENT_DETAILS = 'DEPARTMENT_DETAILS'

	# EMPLOYEE PERMISSION
	EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
	EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
	EMPLOYEE_DELETE = 'EMPLOYEE_DELETE'
	EMPLOYEE_LIST = 'EMPLOYEE_LIST'
	EMPLOYEE_DETAILS = 'EMPLOYEE_DETAILS'

	# CUSTOMER PERMISSION
	CUSTOMER_TYPE_CREATE = 'CUSTOMER_TYPE_CREATE'
	CUSTOMER_TYPE_UPDATE = 'CUSTOMER_TYPE_UPDATE'
	CUSTOMER_TYPE_DELETE = 'CUSTOMER_TYPE_DELETE'
	CUSTOMER_TYPE_LIST = 'CUSTOMER_TYPE_LIST'
	CUSTOMER_TYPE_DETAILS = 'CUSTOMER_TYPE_DETAILS'

	# CUSTOMER PERMISSION
	CUSTOMER_CREATE = 'CUSTOMER_CREATE'
	CUSTOMER_UPDATE = 'CUSTOMER_UPDATE'
	CUSTOMER_DELETE = 'CUSTOMER_DELETE'
	CUSTOMER_LIST = 'CUSTOMER_LIST'
	CUSTOMER_DETAILS = 'CUSTOMER_DETAILS'

	# QUALIFICATION PERMISSION
	QUALIFICATION_CREATE = 'QUALIFICATION_CREATE'
	QUALIFICATION_UPDATE = 'QUALIFICATION_UPDATE'
	QUALIFICATION_DELETE = 'QUALIFICATION_DELETE'
	QUALIFICATION_LIST = 'QUALIFICATION_LIST'
	QUALIFICATION_DETAILS = 'QUALIFICATION_DETAILS'




class OrderPermEnum(Enum):

	# PAYMENT_METHOD PERMISSION
	PAYMENT_METHOD_CREATE = 'PAYMENT_METHOD_CREATE'
	PAYMENT_METHOD_UPDATE = 'PAYMENT_METHOD_UPDATE'
	PAYMENT_METHOD_DELETE = 'PAYMENT_METHOD_DELETE'
	PAYMENT_METHOD_LIST = 'PAYMENT_METHOD_LIST'
	PAYMENT_METHOD_DETAILS = 'PAYMENT_METHOD_DETAILS'

	# ORDER_STATUS PERMISSION
	ORDER_STATUS_CREATE = 'ORDER_STATUS_CREATE'
	ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE'
	ORDER_STATUS_DELETE = 'ORDER_STATUS_DELETE'
	ORDER_STATUS_LIST = 'ORDER_STATUS_LIST'
	ORDER_STATUS_DETAILS = 'ORDER_STATUS_DETAILS'

	# DISCOUNT_TYPE PERMISSION
	DISCOUNT_TYPE_CREATE = 'DISCOUNT_TYPE_CREATE'
	DISCOUNT_TYPE_UPDATE = 'DISCOUNT_TYPE_UPDATE'
	DISCOUNT_TYPE_DELETE = 'DISCOUNT_TYPE_DELETE'
	DISCOUNT_TYPE_LIST = 'DISCOUNT_TYPE_LIST'
	DISCOUNT_TYPE_DETAILS = 'DISCOUNT_TYPE_DETAILS'

	# ORDER PERMISSION
	ORDER_CREATE = 'ORDER_CREATE'
	ORDER_UPDATE = 'ORDER_UPDATE'
	ORDER_DELETE = 'ORDER_DELETE'
	ORDER_LIST = 'ORDER_LIST'
	ORDER_DETAILS = 'ORDER_DETAILS'

	# ORDER_ITEM PERMISSION
	ORDER_ITEM_CREATE = 'ORDER_ITEM_CREATE'
	ORDER_ITEM_UPDATE = 'ORDER_ITEM_UPDATE'
	ORDER_ITEM_DELETE = 'ORDER_ITEM_DELETE'
	ORDER_ITEM_LIST = 'ORDER_ITEM_LIST'
	ORDER_ITEM_DETAILS = 'ORDER_ITEM_DETAILS'

	# PAYMENTMETHOD_DETAIL PERMISSION
	PAYMENTMETHOD_DETAIL_CREATE = 'PAYMENTMETHOD_DETAIL_CREATE'
	PAYMENTMETHOD_DETAIL_UPDATE = 'PAYMENTMETHOD_DETAIL_UPDATE'
	PAYMENTMETHOD_DETAIL_DELETE = 'PAYMENTMETHOD_DETAIL_DELETE'
	PAYMENTMETHOD_DETAIL_LIST = 'PAYMENTMETHOD_DETAIL_LIST'
	PAYMENTMETHOD_DETAIL_DETAILS = 'PAYMENTMETHOD_DETAIL_DETAILS'

	# SHIPPING_ADDRESS PERMISSION
	SHIPPING_ADDRESS_CREATE = 'SHIPPING_ADDRESS_CREATE'
	SHIPPING_ADDRESS_UPDATE = 'SHIPPING_ADDRESS_UPDATE'
	SHIPPING_ADDRESS_DELETE = 'SHIPPING_ADDRESS_DELETE'
	SHIPPING_ADDRESS_LIST = 'SHIPPING_ADDRESS_LIST'
	SHIPPING_ADDRESS_DETAILS = 'SHIPPING_ADDRESS_DETAILS'

	# BILLING_ADDRESS PERMISSION
	BILLING_ADDRESS_CREATE = 'BILLING_ADDRESS_CREATE'
	BILLING_ADDRESS_UPDATE = 'BILLING_ADDRESS_UPDATE'
	BILLING_ADDRESS_DELETE = 'BILLING_ADDRESS_DELETE'
	BILLING_ADDRESS_LIST = 'BILLING_ADDRESS_LIST'
	BILLING_ADDRESS_DETAILS = 'BILLING_ADDRESS_DETAILS'


 

class ProductPermEnum(Enum):

	# PRODUCT PERMISSION
	PRODUCT_CREATE = 'PRODUCT_CREATE'
	PRODUCT_UPDATE = 'PRODUCT_UPDATE'
	PRODUCT_DELETE = 'PRODUCT_DELETE'
	PRODUCT_LIST = 'PRODUCT_LIST'
	PRODUCT_DETAILS = 'PRODUCT_DETAILS'

	# PRODUCT PERMISSION
	DISCOUNT_CREATE = 'DISCOUNT_CREATE'
	DISCOUNT_UPDATE = 'DISCOUNT_UPDATE'
	DISCOUNT_DELETE = 'DISCOUNT_DELETE'
	DISCOUNT_LIST = 'DISCOUNT_LIST'
	DISCOUNT_DETAILS = 'DISCOUNT_DETAILS'

	# PRODUCT_TAG PERMISSION
	PRODUCT_TAG_CREATE = 'PRODUCT_TAG_CREATE'
	PRODUCT_TAG_UPDATE = 'PRODUCT_TAG_UPDATE'
	PRODUCT_TAG_DELETE = 'PRODUCT_TAG_DELETE'
	PRODUCT_TAG_LIST = 'PRODUCT_TAG_LIST'
	PRODUCT_TAG_DETAILS = 'PRODUCT_TAG_DETAILS'

	# ATTRIBUTE_SET PERMISSION
	ATTRIBUTE_SET_CREATE = 'ATTRIBUTE_SET_CREATE'
	ATTRIBUTE_SET_UPDATE = 'ATTRIBUTE_SET_UPDATE'
	ATTRIBUTE_SET_DELETE = 'ATTRIBUTE_SET_DELETE'
	ATTRIBUTE_SET_LIST = 'ATTRIBUTE_SET_LIST'
	ATTRIBUTE_SET_DETAILS = 'QUALIFICATION_DETAILS'

	# ATTRIBUTE_VALUE PERMISSION
	ATTRIBUTE_VALUE_CREATE = 'ATTRIBUTE_VALUE_CREATE'
	ATTRIBUTE_VALUE_UPDATE = 'ATTRIBUTE_VALUE_UPDATE'
	ATTRIBUTE_VALUE_DELETE = 'ATTRIBUTE_VALUE_DELETE'
	ATTRIBUTE_VALUE_LIST = 'ATTRIBUTE_VALUE_LIST'
	ATTRIBUTE_VALUE_DETAILS = 'ATTRIBUTE_VALUE_DETAILS'

	# ATTRIBUTE PERMISSION
	ATTRIBUTE_CREATE = 'ATTRIBUTE_CREATE'
	ATTRIBUTE_UPDATE = 'ATTRIBUTE_UPDATE'
	ATTRIBUTE_DELETE = 'ATTRIBUTE_DELETE'
	ATTRIBUTE_LIST = 'ATTRIBUTE_LIST'
	ATTRIBUTE_DETAILS = 'ATTRIBUTE_DETAILS'

	# BRAND PERMISSION
	BRAND_CREATE = 'BRAND_CREATE'
	BRAND_UPDATE = 'BRAND_UPDATE'
	BRAND_DELETE = 'BRAND_DELETE'
	BRAND_LIST = 'BRAND_LIST'
	BRAND_DETAILS = 'BRAND_DETAILS'

	# CATEGORY PERMISSION
	CATEGORY_CREATE = 'CATEGORY_CREATE'
	CATEGORY_UPDATE = 'CATEGORY_UPDATE'
	CATEGORY_DELETE = 'CATEGORY_DELETE'
	CATEGORY_LIST = 'CATEGORY_LIST'
	CATEGORY_DETAILS = 'CATEGORY_DETAILS'

	# MANUFACTURER PERMISSION
	MANUFACTURER_CREATE = 'MANUFACTURER_CREATE'
	MANUFACTURER_UPDATE = 'MANUFACTURER_UPDATE'
	MANUFACTURER_DELETE = 'MANUFACTURER_DELETE'
	MANUFACTURER_LIST = 'MANUFACTURER_LIST'
	MANUFACTURER_DETAILS = 'MANUFACTURER_DETAILS'

	# COLOR PERMISSION
	COLOR_CREATE = 'COLOR_CREATE'
	COLOR_UPDATE = 'COLOR_UPDATE'
	COLOR_DELETE = 'COLOR_DELETE'
	COLOR_LIST = 'COLOR_LIST'
	COLOR_DETAILS = 'COLOR_DETAILS'

	# SIZE PERMISSION
	SIZE_CREATE = 'SIZE_CREATE'
	SIZE_UPDATE = 'SIZE_UPDATE'
	SIZE_DELETE = 'SIZE_DELETE'
	SIZE_LIST = 'SIZE_LIST'
	SIZE_DETAILS = 'SIZE_DETAILS'

	# PRODUCT_IMAGE PERMISSION
	PRODUCT_IMAGE_CREATE = 'PRODUCT_IMAGE_CREATE'
	PRODUCT_IMAGE_UPDATE = 'PRODUCT_IMAGE_UPDATE'
	PRODUCT_IMAGE_DELETE = 'PRODUCT_IMAGE_DELETE'
	PRODUCT_IMAGE_LIST = 'PRODUCT_IMAGE_LIST'
	PRODUCT_IMAGE_DETAILS = 'PRODUCT_IMAGE_DETAILS'

	# REVIEW_RATING PERMISSION
	REVIEW_RATING_CREATE = 'REVIEW_RATING_CREATE'
	REVIEW_RATING_UPDATE = 'REVIEW_RATING_UPDATE'
	REVIEW_RATING_DELETE = 'REVIEW_RATING_DELETE'
	REVIEW_RATING_LIST = 'REVIEW_RATING_LIST'
	REVIEW_RATING_DETAILS = 'REVIEW_RATING_DETAILS'




class PurchaseReqPermEnum(Enum):
	# PURCHASE_STATUS PERMISSION
	PURCHASE_STATUS_CREATE = 'PURCHASE_STATUS_CREATE'
	PURCHASE_STATUS_UPDATE = 'PURCHASE_STATUS_UPDATE'
	PURCHASE_STATUS_DELETE = 'PURCHASE_STATUS_DELETE'
	PURCHASE_STATUS_LIST = 'PURCHASE_STATUS_LIST'
	PURCHASE_STATUS_DETAIL = 'PURCHASE_STATUS_DETAIL'

	# PURCHASE_REQUEST PERMISSION
	PURCHASE_REQUEST_CREATE = 'PURCHASE_REQUEST_CREATE'
	PURCHASE_REQUEST_UPDATE = 'PURCHASE_REQUEST_UPDATE'
	PURCHASE_REQUEST_DELETE = 'PURCHASE_REQUEST_DELETE'
	PURCHASE_REQUEST_LIST = 'PURCHASE_REQUEST_LIST'
	PURCHASE_REQUEST_DETAIL = 'PURCHASE_REQUEST_DETAIL'

	# PURCHASE_REQUEST_ITEM PERMISSION
	PURCHASE_REQUEST_ITEM_CREATE = 'PURCHASE_REQUEST_ITEM_CREATE'
	PURCHASE_REQUEST_ITEM_UPDATE = 'PURCHASE_REQUEST_ITEM_UPDATE'
	PURCHASE_REQUEST_ITEM_DELETE = 'PURCHASE_REQUEST_ITEM_DELETE'
	PURCHASE_REQUEST_ITEM_LIST = 'PURCHASE_REQUEST_ITEM_LIST'
	PURCHASE_REQUEST_ITEM_DETAIL = 'PURCHASE_REQUEST_ITEM_DETAIL'




class PurchaseFinalPermEnum(Enum):
	# PURCHASE_FINAL PERMISSION
	PURCHASE_FINAL_CREATE = 'PURCHASE_FINAL_CREATE'
	PURCHASE_FINAL_UPDATE = 'PURCHASE_FINAL_UPDATE'
	PURCHASE_FINAL_DELETE = 'PURCHASE_FINAL_DELETE'
	PURCHASE_FINAL_LIST = 'PURCHASE_FINAL_LIST'
	PURCHASE_FINAL_DETAIL = 'PURCHASE_FINAL_DETAIL'

	# PURCHASE_FINAL_ITEM PERMISSION
	PURCHASE_FINAL_ITEM_CREATE = 'PURCHASE_FINAL_ITEM_CREATE'
	PURCHASE_FINAL_ITEM_UPDATE = 'PURCHASE_FINAL_ITEM_UPDATE'
	PURCHASE_FINAL_ITEM_DELETE = 'PURCHASE_FINAL_ITEM_DELETE'
	PURCHASE_FINAL_ITEM_LIST = 'PURCHASE_FINAL_ITEM_LIST'
	PURCHASE_FINAL_ITEM_DETAIL = 'PURCHASE_FINAL_ITEM_DETAIL'

	# PURCHASE_REQUEST_ITEM PERMISSION
	INVENTORY_CREATE = 'INVENTORY_CREATE'
	INVENTORY_UPDATE = 'INVENTORY_UPDATE'
	INVENTORY_DELETE = 'INVENTORY_DELETE'
	INVENTORY_LIST = 'INVENTORY_LIST'
	INVENTORY_DETAIL = 'INVENTORY_DETAIL'




class SiteSettingPermEnum(Enum):
	# MENU_ITEM PERMISSIONS
	MENU_ITEM_CREATE = 'MENU_ITEM_CREATE'
	MENU_ITEM_UPDATE = 'MENU_ITEM_UPDATE'
	MENU_ITEM_DELETE = 'MENU_ITEM_DELETE'
	MENU_ITEM_LIST = 'MENU_ITEM_LIST'
	MENU_ITEM_DETAILS = 'MENU_ITEM_DETAILS'

	# ROLE_MENU PERMISSIONS
	ROLE_MENU_CREATE = 'ROLE_MENU_CREATE'
	ROLE_MENU_UPDATE = 'ROLE_MENU_UPDATE'
	ROLE_MENU_DELETE = 'ROLE_MENU_DELETE'
	ROLE_MENU_LIST = 'ROLE_MENU_LIST'
	ROLE_MENU_DETAILS = 'ROLE_MENU_DETAILS'

	# GENERAL_SETTING PERMISSION
	GENERAL_SETTING_CREATE = 'GENERAL_SETTING_CREATE'
	GENERAL_SETTING_UPDATE = 'GENERAL_SETTING_UPDATE'
	GENERAL_SETTING_DELETE = 'GENERAL_SETTING_DELETE'
	GENERAL_SETTING_LIST = 'GENERAL_SETTING_LIST'
	GENERAL_SETTING_DETAILS = 'GENERAL_SETTING_DETAILS'

	# HOMEPAGE_SLIDER PERMISSION
	HOMEPAGE_SLIDER_CREATE = 'HOMEPAGE_SLIDER_CREATE'
	HOMEPAGE_SLIDER_UPDATE = 'HOMEPAGE_SLIDER_UPDATE'
	HOMEPAGE_SLIDER_DELETE = 'HOMEPAGE_SLIDER_DELETE'
	HOMEPAGE_SLIDER_LIST = 'HOMEPAGE_SLIDER_LIST'
	HOMEPAGE_SLIDER_DETAILS = 'HOMEPAGE_SLIDER_DETAILS'




class SupportPermEnum(Enum):
	# TICKET_DEPARTMENT PERMISSIONS
	TICKET_DEPARTMENT_CREATE = 'TICKET_DEPARTMENT_CREATE'
	TICKET_DEPARTMENT_UPDATE = 'TICKET_DEPARTMENT_UPDATE'
	TICKET_DEPARTMENT_PARTIAL_UPDATE = 'TICKET_DEPARTMENT_PARTIAL_UPDATE'
	TICKET_DEPARTMENT_DELETE = 'TICKET_DEPARTMENT_DELETE'
	TICKET_DEPARTMENT_LIST = 'TICKET_DEPARTMENT_LIST'
	TICKET_DEPARTMENT_DETAILS = 'TICKET_DEPARTMENT_DETAILS'

	# TICKET_PRIORITY PERMISSION
	TICKET_PRIORITY_CREATE = 'TICKET_PRIORITY_CREATE'
	TICKET_PRIORITY_UPDATE = 'TICKET_PRIORITY_UPDATE'
	TICKET_PRIORITY_PARTIAL_UPDATE = 'TICKET_PRIORITY_PARTIAL_UPDATE'
	TICKET_PRIORITY_DELETE = 'TICKET_PRIORITY_DELETE'
	TICKET_PRIORITY_LIST = 'TICKET_PRIORITY_LIST'
	TICKET_PRIORITY_DETAILS = 'TICKET_PRIORITY_DETAILS'

	# TICKET_STATUS PERMISSION
	TICKET_STATUS_CREATE = 'TICKET_STATUS_CREATE'
	TICKET_STATUS_UPDATE = 'TICKET_STATUS_UPDATE'
	TICKET_STATUS_DELETE = 'TICKET_STATUS_DELETE'
	TICKET_STATUS_LIST = 'TICKET_STATUS_LIST'
	TICKET_STATUS_DETAILS = 'TICKET_STATUS_DETAILS'

	# TICKET PERMISSION
	TICKET_CREATE = 'TICKET_CREATE'
	TICKET_UPDATE = 'TICKET_UPDATE'
	TICKET_DELETE = 'TICKET_DELETE'
	TICKET_LIST = 'TICKET_LIST'
	TICKET_DETAILS = 'TICKET_DETAILS'

	# TICKET_DETAIL PERMISSION
	TICKET_DETAIL_CREATE = 'TICKET_DETAIL_CREATE'
	TICKET_DETAIL_UPDATE = 'TICKET_DETAIL_UPDATE'
	TICKET_DETAIL_DELETE = 'TICKET_DETAIL_DELETE'
	TICKET_DETAIL_LIST = 'TICKET_DETAIL_LIST'
	TICKET_DETAIL_DETAILS = 'TICKET_DETAIL_DETAILS'

	# MESSAGE PERMISSION
	MESSAGE_CREATE = 'MESSAGE_CREATE'
	MESSAGE_UPDATE = 'MESSAGE_UPDATE'
	MESSAGE_DELETE = 'MESSAGE_DELETE'
	MESSAGE_LIST = 'MESSAGE_LIST'
	MESSAGE_DETAILS = 'MESSAGE_DETAILS'

	# TASK_TYPE PERMISSION
	TASK_TYPE_CREATE = 'TASK_TYPE_CREATE'
	TASK_TYPE_UPDATE = 'TASK_TYPE_UPDATE'
	TASK_TYPE_DELETE = 'TASK_TYPE_DELETE'
	TASK_TYPE_LIST = 'TASK_TYPE_LIST'
	TASK_TYPE_DETAILS = 'TASK_TYPE_DETAILS'

	# TODO_TASK PERMISSION
	TODO_TASK_CREATE = 'TODO_TASK_CREATE'
	TODO_TASK_UPDATE = 'TODO_TASK_UPDATE'
	TODO_TASK_DELETE = 'TODO_TASK_DELETE'
	TODO_TASK_LIST = 'TODO_TASK_LIST'
	TODO_TASK_DETAILS = 'TODO_TASK_DETAILS'






