# Generated by Django 4.2.4 on 2025-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={},
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
