# Generated by Django 4.2.4 on 2025-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_group_options_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='primarygroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subledgeraccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
