# Generated by Django 4.2.4 on 2025-08-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ledgeraccount_name_alter_primarygroup_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentvoucher',
            old_name='credit_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='debit_amount',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='ledger',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='expense_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='expense_ledger_paymentvoucher', to='accounts.ledgeraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='payment_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='payment_ledger_paymentvoucher', to='accounts.ledgeraccount'),
            preserve_default=False,
        ),
    ]
