# Generated by Django 4.2.4 on 2025-08-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_credit_amount_paymentvoucher_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptvoucher',
            old_name='credit_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='debit_amount',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='ledger',
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='income_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_voucher_payment', to='accounts.ledgeraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='receipt_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_voucher_receipt', to='accounts.ledgeraccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='account/ReceiptVoucher/'),
        ),
    ]
