# Generated by Django 4.2.4 on 2025-08-09 04:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_sku_alter_product_slug'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, help_text='Reason for adjustment (e.g., Damaged, Stock count correction, Lost, Extra stock found)', max_length=255)),
                ('reference_number', models.CharField(blank=True, help_text='Optional reference for tracking', max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='product.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
