# Generated by Django 4.2.4 on 2025-08-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='reference_number',
        ),
    ]
