# Generated by Django 4.2.4 on 2025-08-07 20:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_supplier_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone_number'),
        ),
    ]
